version: '3.8'

services:
  backend_chatpdf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    env_file:
      - .env 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge